name = "defihaus"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
CHECKIN_HOUR = "15"
CHECKOUT_HOUR = "11"
SHELLY_DEVICE_ID = "a085e3c9b840"
SHELLY_SERVER = "shelly-247-eu.shelly.cloud"
ACCESS_KEY = "dh-narv-2026-secreto"
ICAL_URL = "https://www.airbnb.com/calendar/ical/1574837156020290632.ics?t=0c1f056f3ec645619cfa39f465d01004&locale=en"
ICAL_URL_2 = "https://www.airbnb.mx/calendar/ical/1588504890958663315.ics?t=8a3bf5f356484ded974939146e4a6e3e"
NTFY_TOPIC = "defihaus-narvarte-door"
